spring:
  main:
    allow-bean-definition-overriding: true
  shell:
    interactive:
      enabled: true
    jline:
      enabled: true
      ansi: always
    terminal:
      type: xterm-256color
    config:
      jansi:
        enabled: true
  output:
    ansi:
      enabled: always

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(%level){bright} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"